package br.com.sisEducar.modulos.RH.utils;

import javax.faces.bean.ManagedBean;

@ManagedBean(name="constantesRH")
public class ConstantesRH 
{
	
	/* Constantes Tipo de Usuario */
	private int TIPO_USUARIO_ADMIN = 1;
	private int TIPO_USUARIO_PROFESSOR = 2;
	private int TIPO_USUARIO_ALUNO = 3;
	
	/* Constantes tipo de pessoa */
	private int TIPO_PESSOA_FISICA = 10;
	private int TIPO_PESSOA_JURIDICA = 11;
	
	/* Sexo */
	private int SEXO_MASCULINO = 20;
	private int SEXO_FEMININO = 21;
	
	/* 	Estado Civil*/
	private int ESTADO_CIVIL_SOLTEIRO = 30;
	private int ESTADO_CIVIL_CASADO = 31;
	private int ESTADO_CIVIL_SEPARADO = 33;
	private int ESTADO_CIVIL_DIVORCIADO = 34;
	private int ESTADO_CIVIL_VIUVO = 35;
	
	/* Formação Acadêmica*/
	private int ENSINO_FUNDAMENTAL_INCOMPLETO = 40;
	private int ENSINO_FUNDAMENTAL_COMPLETO = 41;
	private int ENSINO_MEDIO_INCOMPLETO = 42;
	private int ENSINO_MEDIOL_COMPLETO = 43;
	private int ENSINO_TECNICO_INCOMPLETO = 44;
	private int ENSINO_TECNICO_COMPLETO = 45;
	private int ENSINO_SUPERIOR_INCOMPLETO = 46;
	private int ENSINO_SUPERIOR_COMPLETO = 47;
	private int MESTRADO = 48;
	private int DOUTORADO = 49;
	private int POS_DOUTORADO = 50;
	

	//Getters and Setters
	public int getTIPO_USUARIO_ADMIN() 									{return TIPO_USUARIO_ADMIN;}
	public void setTIPO_USUARIO_ADMIN(int tIPO_USUARIO_ADMIN) 			{TIPO_USUARIO_ADMIN = tIPO_USUARIO_ADMIN;}
	public int getTIPO_USUARIO_PROFESSOR() 								{return TIPO_USUARIO_PROFESSOR;}
	public void setTIPO_USUARIO_PROFESSOR(int tIPO_USUARIO_PROFESSOR) 	{TIPO_USUARIO_PROFESSOR = tIPO_USUARIO_PROFESSOR;}
	public int getTIPO_USUARIO_ALUNO() 								  	{return TIPO_USUARIO_ALUNO;}
	public void setTIPO_USUARIO_ALUNO(int tIPO_USUARIO_ALUNO) 		    {TIPO_USUARIO_ALUNO = tIPO_USUARIO_ALUNO;}
	public int getTIPO_PESSOA_FISICA() 								   	{return TIPO_PESSOA_FISICA;}
	public void setTIPO_PESSOA_FISICA(int tIPO_PESSOA_FISICA) 			{TIPO_PESSOA_FISICA = tIPO_PESSOA_FISICA;}
	public int getTIPO_PESSOA_JURIDICA() 								{return TIPO_PESSOA_JURIDICA;}
	public void setTIPO_PESSOA_JURIDICA(int tIPO_PESSOA_JURIDICA) 		{TIPO_PESSOA_JURIDICA = tIPO_PESSOA_JURIDICA;}
	public int getENSINO_SUPERIOR_INCOMPLETO() 									{return ENSINO_SUPERIOR_INCOMPLETO;}
	public void setENSINO_SUPERIOR_INCOMPLETO(int eNSINO_SUPERIOR_INCOMPLETO) 	{ENSINO_SUPERIOR_INCOMPLETO = eNSINO_SUPERIOR_INCOMPLETO;}
	public int getENSINO_SUPERIOR_COMPLETO() 									{return ENSINO_SUPERIOR_COMPLETO;}
	public void setENSINO_SUPERIOR_COMPLETO(int eNSINO_SUPERIOR_COMPLETO) 		{ENSINO_SUPERIOR_COMPLETO = eNSINO_SUPERIOR_COMPLETO;}
	public int getSEXO_MASCULINO() 										{return SEXO_MASCULINO;}
	public void setSEXO_MASCULINO(int sEXO_MASCULINO) 					{SEXO_MASCULINO = sEXO_MASCULINO;}
	public int getSEXO_FEMININO() 										{return SEXO_FEMININO;}
	public void setSEXO_FEMININO(int sEXO_FEMININO) 					{SEXO_FEMININO = sEXO_FEMININO;}
	public int getESTADO_CIVIL_SOLTEIRO() 								{return ESTADO_CIVIL_SOLTEIRO;}
	public void setESTADO_CIVIL_SOLTEIRO(int eSTADO_CIVIL_SOLTEIRO) 	{ESTADO_CIVIL_SOLTEIRO = eSTADO_CIVIL_SOLTEIRO;}
	public int getESTADO_CIVIL_CASADO() 								{return ESTADO_CIVIL_CASADO;}
	public void setESTADO_CIVIL_CASADO(int eSTADO_CIVIL_CASADO) 		{ESTADO_CIVIL_CASADO = eSTADO_CIVIL_CASADO;}
	public int getESTADO_CIVIL_SEPARADO() 								{return ESTADO_CIVIL_SEPARADO;}
	public void setESTADO_CIVIL_SEPARADO(int eSTADO_CIVIL_SEPARADO) 	{ESTADO_CIVIL_SEPARADO = eSTADO_CIVIL_SEPARADO;}
	public int getESTADO_CIVIL_DIVORCIADO() 							{return ESTADO_CIVIL_DIVORCIADO;}
	public void setESTADO_CIVIL_DIVORCIADO(int eSTADO_CIVIL_DIVORCIADO) {ESTADO_CIVIL_DIVORCIADO = eSTADO_CIVIL_DIVORCIADO;}
	public int getESTADO_CIVIL_VIUVO() 									{return ESTADO_CIVIL_VIUVO;}
	public void setESTADO_CIVIL_VIUVO(int eSTADO_CIVIL_VIUVO) 			{ESTADO_CIVIL_VIUVO = eSTADO_CIVIL_VIUVO;}
	public int getENSINO_FUNDAMENTAL_INCOMPLETO() 						{return ENSINO_FUNDAMENTAL_INCOMPLETO;}	
	public void setENSINO_FUNDAMENTAL_INCOMPLETO(int eNSINO_FUNDAMENTAL_INCOMPLETO) {ENSINO_FUNDAMENTAL_INCOMPLETO = eNSINO_FUNDAMENTAL_INCOMPLETO;}
	public int getENSINO_FUNDAMENTAL_COMPLETO() 									{return ENSINO_FUNDAMENTAL_COMPLETO;}
	public void setENSINO_FUNDAMENTAL_COMPLETO(int eNSINO_FUNDAMENTAL_COMPLETO) 	{ENSINO_FUNDAMENTAL_COMPLETO = eNSINO_FUNDAMENTAL_COMPLETO;}
	public int getENSINO_MEDIO_INCOMPLETO() 										{return ENSINO_MEDIO_INCOMPLETO;}
	public void setENSINO_MEDIO_INCOMPLETO(int eNSINO_MEDIO_INCOMPLETO) 			{ENSINO_MEDIO_INCOMPLETO = eNSINO_MEDIO_INCOMPLETO;}
	public int getENSINO_MEDIOL_COMPLETO() 											{return ENSINO_MEDIOL_COMPLETO;}
	public void setENSINO_MEDIOL_COMPLETO(int eNSINO_MEDIOL_COMPLETO) 				{ENSINO_MEDIOL_COMPLETO = eNSINO_MEDIOL_COMPLETO;}
	public int getENSINO_TECNICO_INCOMPLETO() 										{return ENSINO_TECNICO_INCOMPLETO;}
	public void setENSINO_TECNICO_INCOMPLETO(int eNSINO_TECNICO_INCOMPLETO) 		{ENSINO_TECNICO_INCOMPLETO = eNSINO_TECNICO_INCOMPLETO;}
	public int getENSINO_TECNICO_COMPLETO() 										{return ENSINO_TECNICO_COMPLETO;}
	public void setENSINO_TECNICO_COMPLETO(int eNSINO_TECNICO_COMPLETO) 			{ENSINO_TECNICO_COMPLETO = eNSINO_TECNICO_COMPLETO;}
	public int getMESTRADO() 														{return MESTRADO;}
	public void setMESTRADO(int mESTRADO) 											{MESTRADO = mESTRADO;}
	public int getDOUTORADO() 														{return DOUTORADO;}
	public void setDOUTORADO(int dOUTORADO) 										{DOUTORADO = dOUTORADO;}
	public int getPOS_DOUTORADO() 													{return POS_DOUTORADO;}
	public void setPOS_DOUTORADO(int pOS_DOUTORADO) 								{POS_DOUTORADO = pOS_DOUTORADO;}
}
